Bug/add legacy support
fivetran/dbt_lever_source pull request #27
Opened 2024-10-17 23:19 UTC by fivetran-catfritz

## PR Overview
**This PR will address the following Issue/Feature:**

**This PR will result in the following new package version:**

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [ ] dbt run –full-refresh && dbt test
- [ ] dbt run (if incremental models are present) && dbt test

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked, tagged, and properly assigned
- [ ] All necessary documentation and version upgrades have been applied
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)
- [ ] BuildKite integration tests are passing
- [ ] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2024-10-21 23:37 UTC, fivetran-catfritz commented on dbt_project.yml
> -  lever_using_requisitions: true
These are true by default, so should not be included here.

2024-10-22 21:30 UTC, fivetran-reneeli reviewed
Thanks @fivetran-catfritz ! Just had some comments

2024-10-22 21:30 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- Fixed an issue where the dbt package would error due to a missing `CONTACT_LINK` source table for users without source data, even though it was enabled in the Fivetran Connector. A null-filled tabl
```suggestion
- Fixed an issue where the dbt package would error due to a missing `CONTACT_LINK` source table for users without the titular source data, even if it was enabled in the Fivetran Connector. A null-filled table will now be generated in such cases.
```

2024-10-22 21:30 UTC, fivetran-reneeli commented on integration_tests/dbt_project.yml
> +    lever_users_identifier: "users"
Shall we also include `lever_interviewer_user_identifier` and `lever_user_identifier` to test as well? we can comment it out, but i think it is worthwhile to keep. Also, I noticed it's retained in the transforms branch.

2024-10-23 17:27 UTC, fivetran-catfritz reviewed
Thanks @fivetran-reneeli! I have updated.

2024-10-23 18:38 UTC, fivetran-reneeli approved these changes
Just remembered one thing-- to uncollapse the dropdowns in the README. Other than that, looks good to go!

2024-10-24 20:29 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz thanks for working through this PR! I have a few change requests and comments before this is ready to go. Let me know if you have any questions. Thanks!

2024-10-24 20:29 UTC, fivetran-joemarkiewicz commented on models/tmp/stg_lever__interviewer_user_tmp.sql
> +}}
For some reason this isn't working as I would expect when testing on two different schemas (one with `interviewer_user` and one with `interview_user`. It seems to work when `interviewer_user` is present, but not `interview_user`. 

Strangely enough, the `users` vs `user` works without an issue. Would you be able to look into this and see what could be the cause or if I may be missing something.

2024-10-25 15:00 UTC, fivetran-catfritz reviewed
@fivetran-joemarkiewicz Thanks for the review. Made the updates!

2024-10-25 18:38 UTC, fivetran-joemarkiewicz approved these changes
LGTM

2024-10-28 13:39 UTC, fivetran-catfritz reviewed
@fivetran-joemarkiewicz I added the null tests back!

2024-10-28 15:09 UTC, fivetran-joemarkiewicz approved these changes
Thanks @fivetran-catfritz! Approved with one last request to add an additional entry to the CHANGELOG for the test modification/updates.

2024-10-28 15:34 UTC, fivetran-catfritz commented on CHANGELOG.md
> +- Added the `source_relation` column in each staging model to identify the origin of each field, utilizing the `fivetran_utils.source_relation` macro.
Added!

2024-10-28 15:57 UTC, merged