Add support for lack of posting_tag table, fixes #4
fivetran/dbt_lever_source pull request #5
Opened 2021-03-11 14:07 UTC by nelsonauner

Some comments based on requests in issue discussion:

> Disable staging models, both stg and tmp.
✔️  Done
> Update README, under a new "Disabling Models" section
✔️  Done
> Add variable to dbt_project.yml file, as an example. Default should be true.
🙅 I didn't do this, because I wanted to follow the pattern of the existing optional model (`lever_using_requisitions`) which is NOT included in the `dbt_project.yml` and the README is clear that these config vars should only be added if they should be disabled.

2021-03-11 14:13 UTC, nelsonauner commented on README.md
> +# (rest of file)
It's not super clear if these vars should be nested under the `lever_source` section or not, so maybe I could make that more explicit in the example ? e.g. 

```yml
...
vars:

  # add lever_using_{var} here 

  lever_source:
    application: "{{ source('lever', 'application') }}"
    archive_reason: "{{ source('lever', 'archive_reason') }}"
    feedback_form_field: "{{ source('lever', 'feedback_form_field') }}"
    feedback_form: "{{ source
```

2021-03-11 23:57 UTC, fivetran-kristin requested changes
Hey @nelsonauner, thanks for this!

We've made the decision to explicitly define variables in the project.yml file (even if they're set to the default value), so that users have an example of what the format and structure should be.  Can you update please?

2021-03-11 23:57 UTC, fivetran-kristin commented on README.md
> +# (rest of file)
Here they're structured as global variables, and also part of the reason why we prefixed with `lever_`. 

It's good to hear feedback that it's a little confusing.  The reason we have them here as global variables is so that users don't have to define the variable twice, under both `lever` and `lever_source`. 

cc: @fivetran-jamie fyi on global variable feedback.

2021-03-12 23:44 UTC, nelsonauner commented on README.md
> +# (rest of file)
That makes sense! - but that's _not_ how they're defined in https://github.com/fivetran/dbt_lever/blob/master/dbt_project.yml#L37 - in fact - I think that's a bug in the repo, because the way it's nested, I think it simply won't work with `{{ var(lever_using_requisitions) }}` since it's nested under `lever:` section.

2021-03-13 00:02 UTC, nelsonauner commented
@fivetran-kristin Thank you for the feedback! I have made the requested changes

2021-03-16 23:53 UTC, fivetran-jamie approved these changes
Looks good to me!

2021-03-16 23:58 UTC, merged